### ISSUE TITLE
关于多处章节跳转处的命名 以及 目录命名的想法

### ISSUE THREAD

**Issue by lyonnee** [rustx-labs/effective-rust-cn#11]
第1条, 第12条这种描述很混乱, 并且"条"字用在这些地方更不准确了.
用章节来表示整个结构也会更直观.

例如:
目录的表示:
```
- 4.类型 (章)
 |- 4.1 使用类型系统表达你的数据结构 (节)
 |- 4.2 使用类型系统表达常见行为
 ....
- 5.特性
 |- 5.1 属性标准库特性
......
```

连接跳转:
```mkdown
在 Rust 的类型系统中，行为首次出现的地方就是将方法添加到数据结构上：这些方法是对该类型实例的操作，通过 `self` 标识。这种方式以对象导向的方式将相关的数据和代码封装在一起，这与其他语言中的做法相似；然而，在 Rust 中，方法不仅可以添加到`结构体`类型上，也可以添加到`枚举`类型上，这与 Rust 枚举的普遍性质相符（[4.1节]）。
```

**Comment by lispking** [comment]
有些道理，不过其他Effective类的书也是这么翻译，而且与书的标题也能映射上，不过当务之急是全书翻译后，在审校的时候统一修改更好一些

**Comment by lispking** [comment]
一开始以【方法1】【方法2】...【方法N】来命名，有同学提了 #3 的建议，后来再看了其他语言也是用 **第 xx 条** 这种译法就改了

**Comment by lyonnee** [comment]
> 一开始以【方法1】【方法2】...【方法N】来命名，有同学提了 #3 的建议，后来再看了其他语言也是用 **第 xx 条** 这种译法就改了

好吧, 那按就先按这个规则来

**Comment by lispking** [comment]
恩恩，感谢提建议，可以先以这个规则翻译，等后续再统计修改，毕竟嘛，书的标题也是写了35条，如果以章节来命名的话，可能不好提示当前是第几条，如果以章节来命名的话，还要考虑整书该如何调整的问题，涉及是整个框架的调整了
