### ISSUE TITLE
Item 10: Familiarize yourself with standard traits

### ISSUE THREAD

**Issue by lyonnee** [rustx-labs/effective-rust-cn#21]

**Comment by lispking** [comment]
@lyonnee 这边翻译还顺利不

之前 @sweet2honey 在 #13 也有意向翻译此章节，需要 @sweet2honey 帮忙不 ^_^

**Comment by lyonnee** [comment]
> @lyonnee 这边翻译还顺利不
> 
> 之前 @sweet2honey 在 #13 也有意向翻译此章节，需要 @sweet2honey 帮忙不 ^_^

前几天比较忙, 所以耽搁了. 这两天会提交上

**Comment by lyonnee** [comment]
@lispking 抱歉最近确实有事情还会耽搁, 还是麻烦让@sweet2honey帮忙翻译了吧

**Comment by sweet2honey** [comment]
> @lispking 抱歉最近确实有事情还会耽搁, 还是麻烦让@sweet2honey帮忙翻译了吧

我可以从你断的下一节帮你续上哈 你翻译到哪啦

**Comment by lyonnee** [comment]
> > @lispking 抱歉最近确实有事情还会耽搁, 还是麻烦让@sweet2honey帮忙翻译了吧
> 
> 我可以从你断的下一节帮你续上哈 你翻译到哪啦

就这些了
[item10-standard-traits.md](https://github.com/user-attachments/files/15598200/item10-standard-traits.md)

**Comment by sweet2honey** [comment]
@lispking 我接一下 @lyonnee 剩下下的部分吧 ，谢谢两位

**Comment by lispking** [comment]
辛苦 @sweet2honey ，感谢大家为Rust社区做贡献，咱们一起努力加油

**Comment by lispking** [comment]
#36

**Comment by sweet2honey** [comment]
@lispking 可以加个wx好友学习交流吗，我之前在你公众号留言好像没回复

**Comment by lispking** [comment]
哈哈，公众号都有回复，可能是让你来这里留言，你的wx号发一下，我来加你

**Comment by sweet2honey** [comment]
> 哈哈，公众号都有回复，可能是让你来这里留言，你的wx号发一下，我来加你

honeyholic
