### ISSUE TITLE
Item 6: Embrace the newtype pattern

### ISSUE THREAD

**Issue by jimzk** [rustx-labs/effective-rust-cn#22]
https://www.lurklurk.org/effective-rust/newtype.html

**Comment by lispking** [comment]
#6 @jimzk 注意看之前这里的问题

**Comment by jimzk** [comment]
#6 说的问题其实是在Item 5里

**Comment by lispking** [comment]
不错，确实如此，不过有可能是作者最近有调整过章节，发现最近书的图标提示都改了
