### ISSUE TITLE
Item 27: Document public interfaces

### ISSUE THREAD

**Issue by liyan-ah** [rustx-labs/effective-rust-cn#28]
英文原文：https://www.lurklurk.org/effective-rust/documentation.html

**Comment by liyan-ah** [comment]
准备从 Item 27 着手参与翻译。如果一切顺利的话，应该于近两周完成。

又及：
本项目是否涉及版权风险🐶

**Comment by lispking** [comment]
不用担心，网上有很多类似的书，毕竟作者的书没有表明不让翻译。（跟作者沟通过，作者表示欢迎翻译，所以为什么翻译的同时做好原文对应的是链接，毕竟作者有挂CC认证，遵循CC认证即可）

关键是帮助到社区，欢迎为 Rust 社区贡献一份力量。

**Comment by liyan-ah** [comment]
搞了个初版，感觉不太通顺。本周再调整下。

**Comment by lispking** [comment]
好的，辛苦了

**Comment by liyan-ah** [comment]
https://github.com/rustx-labs/effective-rust-cn/pull/33
