### ISSUE TITLE
item的翻译

### ISSUE THREAD

**Issue by Egg12138** [rustx-labs/effective-rust-cn#3]
item X 翻译成 第X条 会不会更好些？本书title连带也能改译成《Effective Rust: 改善Rust代码的35条建议》（虽然有点细枝末节了）

**Comment by lispking** [comment]
Python 那本书是叫翻译成 第 X 条（周末想着一并改），所以，已经把书名改成类似 Python版：编写高质量 Rust 代码的 35 个有效方法，这样看起来更有吸引力

**Comment by lispking** [comment]
欢迎提 PR 过来修改下

**Comment by lispking** [comment]
https://github.com/rustx-labs/effective-rust-cn/pull/2
@Egg12138 最近有热心的小伙伙提了一个PR，在原书基础上也加了一些案例，整体看起来会更有趣

**Comment by lispking** [comment]
已修改，感谢提建议
