### ISSUE TITLE
Item 22: Minimize visibility

### ISSUE THREAD

**Issue by dzhang28** [rustx-labs/effective-rust-cn#51]
英文原文：https://www.lurklurk.org/effective-rust/visibility.html

**Comment by dzhang28** [comment]
Closed due to very limited bandwidth.

**Comment by yuqiang-yuan** [comment]
@lispking 我想认领这个条目，需要重新开一个？还是直接在这里分配给我？

**Comment by lispking** [comment]
> @lispking 我想认领这个条目，需要重新开一个？还是直接在这里分配给我？

@yuqiang-yuan 已分配，感谢支持

**Comment by lispking** [comment]
https://github.com/rustx-labs/effective-rust-cn/pull/57
