### ISSUE TITLE
Item 5的表述可能有些错误，关于强制隐式类型转换中提及的`converting an array to a slice`

### ISSUE THREAD

**Issue by CNCSMonster** [rustx-labs/effective-rust-cn#6]
![ER_ERROR](https://github.com/rustx-labs/effective-rust-cn/assets/99234657/8ff24e44-a94c-405a-9b88-0efe0a5b1604)
原文Item 6中 说隐式强制类型转换包括数组类型到切片类型的转换。
在笔者的试验下:
Rust版本:`cargo 1.79.0-nightly (c93926759 2024-04-23)`
示例1:
```Rust
let arr: [i32; 2] = [1, 2];
let slice: &[i32] = arr;
```
编译失败,说明该版本下不能实现array类型到slice类型的强制转换
示例2:
```Rust
let arr_ref: &[i32; 2] = &[1, 2];
let slice: &[i32] = arr_ref;
```
说明能够实现的是从array类型的引用到slice类型的隐式强制转换。

所以原文可能是作者的笔误。为了验证这一点,笔者切换到书中作者的Rust版本`1.60`使用rustc编译两个用例得到了一样的结果。

**Comment by lispking** [comment]
good job，感谢支持，欢迎一起翻译

**Comment by lispking** [comment]
作者最近的书籍有些变动，目前变成 item 5了

**Comment by lispking** [comment]
issue #14 在翻译中，这里先关了
