### ISSUE TITLE
【typo】第二章 第10条

### ISSUE THREAD

**Issue by w4ngzhen** [rustx-labs/effective-rust-cn#77]
https://github.com/rustx-labs/effective-rust-cn/blob/main/src/chapter_2/item10-std-traits.md?plain=1#L138

> 如果你的类型比较大，实现 `Copy` 可能是个坏主意。`Copy` 的基本约定是安比特位拷贝是合法的

这里“安比特位拷贝”应改为“按比特位拷贝”

**Comment by lispking** [comment]
可以直接提pr修改

**Comment by lispking** [comment]
https://github.com/rustx-labs/effective-rust-cn/pull/78
